server:
  port: 3001
grpc:
  security:
    auth:
      enabled: false
spring:
  datasource:
    url: jdbc:mysql://localhost:33060/akki?enabledTLSProtocols=TLSv1.2
    username: root
    password: root
    hikari:
      leak-detection-threshold: 60000
      minimum-idle: 2
      maximum-pool-size: 100